### ISSUE TITLE
Checkboxes Fields Display Warning

### ISSUE THREAD

**Issue by enxaqueca** [yikesinc/yikes-inc-easy-mailchimp-extender#362]
Field Type Checkboxes display the following warning:
Warning: in_array() expects parameter 2 to be array, string given in /wp-content/plugins/yikes-inc-easy-mailchimp-extender/public/partials/shortcodes/process_form_shortcode.php on line 591
value="Option 1"> Option 1
where Option 1 is whatever option is supposed to be shown beside the checkbox.
I'm attaching a screenshot, hope it helps.
Thanks!
![screen shot 2015-09-28 at 11 43 23 am](https://cloud.githubusercontent.com/assets/14874437/10139011/5c373716-65d7-11e5-96c3-cd9de3d54692.png)

**Comment by EvanHerman** [comment]
Hi Enxaqueca,

Is that just a standard check box field? Does the error still persist if you set one of the check boxes to be checked by default?

I will look into this issue now.


Thanks,
Evan

**Comment by EvanHerman** [comment]
I have just pushed out an update which should repair this issue. Feel free to re-download the latest release found here:

https://cloudup.com/files/iU2qFFvl2li/download

Thanks,
Evan

**Comment by enxaqueca** [comment]
Evan, the warning is gone but so are the checkboxes. Without them, subscribers are unable to choose a group within the List.

**Comment by EvanHerman** [comment]
Hi,

I'm not seeing that issue. I still have checkboxes on my end. Did you remove the interest group from the signup form? You may want to try removing it and re-adding the field to the form after updating to the latest release. 

Evan

**Comment by enxaqueca** [comment]
Evan, I'm sorry, it's not an issue after all. I've gotten a bit confused with the interface after the update and it took me a while to see the Interest Groups tab. I then added all the interest groups to the Form and now it shows up in the front end.

**Comment by EvanHerman** [comment]
Hi enxaqueca,

No worries. I'm glad things are working on your end and we didn't have a larger issue at hand.

Let us know if you run into any other issues! If you find the plugin useful, we'd love it if you could leave us a review so others will take note of our work: https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender


Thanks again,
Evan

**Comment by enxaqueca** [comment]
Not only will I happily do that, but I would be glad to contribute in the translation the new version to pt_BR if needed. Is there a translation file?

**Comment by TheTracyL** [comment]
Yes! We would LOVE that. Thank you so much! You can find the language files in this folder:
https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging/plugin_core/languages

We really appreciate it!
-Tracy

**Comment by enxaqueca** [comment]
Good news - the translation of the new version to pt_BR is ready as promised. Is it alright to upload the .po and .mo here?

**Comment by TheTracyL** [comment]
Fantastic! Yes, you can upload the files and I will incorporate them into the plugin.

Thank you so much!
-Tracy

**Comment by TheTracyL** [comment]
Alternatively, you can do a pull-request to the staging branch and I can merge your files that way.

**Comment by enxaqueca** [comment]
When trying to upload them here, I get the message "Unfortunately, we don't support that file type". I'll try and find the staging branch to do the pull-request. If I fail, I'll attach them to your GitHub Profile's email address. Please convey my thanks to all folks involved in the making of this plugin.

**Comment by TheTracyL** [comment]
Emailing it to info@yikesinc.com will work great if you can't do the pull request. 

We really appreciate your contribution!

**Comment by enxaqueca** [comment]
Done. I emailed them. Thank you very much.

**Comment by TheTracyL** [comment]
Thank you! I already received and added them. :-)

**Comment by enxaqueca** [comment]
Hi. I just installed the plugin from the WordPress repository (wp-admin > plugins > add new > search > install) in another site. When I unchecked the check boxes in my interest groups, the same error/Warning appeared, as noted above. 

I then uninstalled and reinstalled an earlier version from my computer, which had been downloaded from the link above - and now the Warning is gone.

Can this be an issue with the plugin's newest version?

Thank you.

**Comment by EvanHerman** [comment]
Hi,

You shouldn't be seeing any errors in the dashboard. We've cleared up the issue in the 6.0.2.4 release, so I'm not sure why you are still seeing it. Any chance you can provide is with temporary login or an exact copy of the form so we can try replicating the issue?


Thanks,
Evan

**Comment by enxaqueca** [comment]
To whom shall I email the login credentials?

**Comment by EvanHerman** [comment]
Feel free to email me at Evan@yikesinc.com and we can discuss what might be going on.

Thanks!
Evan

**Comment by enxaqueca** [comment]
Hi Evan,

The error does not persist when a check box is checked for each interest
group. This is the same issue that I had originally reported back in
September and appeared to have been fixed after I installed the Version
from the download link you posted in the thread.
