### ISSUE TITLE
Popup add on fails: "It looks like the popups table is missing."

### ISSUE THREAD

**Issue by gallilaw** [yikesinc/yikes-inc-easy-mailchimp-extender#546]
I just ordered and installed the popups add-on, but it won't begin to work.

I have a WP multisite system on which the add on was installed and network activated without a problem. But the add on won't run because it reports that "It looks like the popups table is missing." and suggests re-activating. I de-activated, then re-activated; then when that didn't work I uninstalled (deleted), re-installed, activated... Same result -- tables missing error.

I've been to the Settings page but nothing appears into which I could plug the popup addon's license key. There is no Addon Settings section and no link to a forms customizer.

Any ideas? I've had no problem installing any other plugins.

**Comment by EvanHerman** [comment]
Hi Gallilaw,

I think the table definitions are a bit too strict when the plugin is activated, which may be what is causign the issues on your specific install. It seems to work on newer versions of PHP, but with the later versions the table creation tends to run into a few hiccups.

I am going to work on a patch and push out an update. When the update is out, you should be able to login to our site and re-download the latest version of the plugin. I should have an update out in the next couple of hours. (This was something we recently went back and updated in the base plugin, so if that is working for you - I will just need to implement that methodology into the pop up add-on as well)


Thanks!
Evan

**Comment by TheTracyL** [comment]
Hi Gallilaw,

We fixed this issue. Login to your account  and try redownloading.

Thank you!
-Tracy

**Comment by gallilaw** [comment]
Thanks for the note.

The fix did enable the popup function to appear, and at first it seemed 
to be working...

...but then I noticed that when a popup did appear in the browser, the 
styling I had applied (in the content editor for the pre-form and 
post-form areas) had been stripped away. At least six times I placed two 
short paragraphs and styled a short headline to be 16 pt bold, centered 
and red. None of the styling stuck.

No "save" button appeared anywhere, and if I closed out of the popup 
pages or clicked the "Update Popup" link, as soon as I returned to the 
popup settings pages I would see that the styling had gone away and the 
text had reverted to a single unformatted block.


Best wishes.

Richard Galli
http://richardgalli.com

**Comment by TheTracyL** [comment]
Hi Richard,

Thank you for letting me know. We will look into this.

-Tracy

**Comment by EvanHerman** [comment]
I have just pushed out a version 1.1.1 release, which should have this resolved. Please go ahead and update to the latest release and re-test. The HTML was being stripped each time things were saved in the database.

Thanks!
Evan

**Comment by gallilaw** [comment]
I have kept these communications via email rather than public post 
because you folks seem to be very responsive and I didn't want to 
clutter up the record, but...

After installing the 1.1.1 update, now I get this again:

"It looks like the popups table is missing. Please de-activate and 
re-activate this extension to attempt to re-create the table. If the 
error persists, please get in touch with the Yikes Inc. support team."


When I first installed the popup app that message was all I got. Then 
your version 1.1.0 got me into the popup menus, but the styling editor 
had no save button nor any other save capability, and the resulting text 
seen in a browser was an unformatted mess. Now the 1.1.1 update has 
returned me to a non-functional popup extension whose tables are 
missing. Ouch.

I tried installing the 1.1.1update over the current install and that 
failed. I deleted the current install and installed the 1.1.1 and it got 
me to the table missing message. I de-activated and re-activated 1.1.1 
and it returned the same message.

Let me know if there's anything I can do to help in the diagnosing.


While I have your attention: Is there a way to put the popup into a test 
mode?  The minimum "reset" option is one day (as I recall, not being 
able to check it now) and it would help if we during the design phase we 
could choose a shorter reset time, like ten seconds or similar.

Best wishes.

Richard Galli
http://richardgalli.com

**Comment by TheTracyL** [comment]
FYI these emails post publicly to https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/546#issuecomment-234626826

**Comment by TheTracyL** [comment]
Evan can troubleshoot the forms table issue.

The save button is the "Update Popup" button. That will save all content or settings edits.

When testing, I put it in "Aggressive" mode (found on the settings page). That will trigger the popup every time the page is loaded. 

Thank you!
-Tracy

**Comment by EvanHerman** [comment]
Nothing was changed in terms of the table definitions in version 1.1.0 to 1.1.1. The table types are still set to a more basic type (eg: TEXT instead of LONGTEXT).

What version of PHP is your site running?


Thanks,
Evan

**Comment by gallilaw** [comment]
Hello again.

When I was able to get access to the popup editor in the version before 
1.1.1, I did try saving with the "update" button several times but the 
save never stuck.

I am running my sites at SiteGround and have had good experience with them.

Cpanel Version Manager reports the PHP version for the public html 
directory is 5.6.23

In Version Manager page there is an unselected radio button for version 
7.0.8 but I do not know if pressing the that option and saving will make 
everything good to go. Want me to try it?

--------
"SiteGround has implemented a unique server setup that allows each 
customer to choose which version of PHP to use for his / her account. 
What is more, the customer can even use different PHP versions for 
different directories in one and the same hosting account.

The PHP versions currently supported are: PHP 5.3, PHP 5.4, PHP 5.5, PHP 
5.6, and PHP 7.0."
---------


Best wishes.

Richard Galli
http://richardgalli.com

**Comment by EvanHerman** [comment]
The settings probably weren't saving because the table didn't exist and there was no where for the options/settings to save to.

If you want to email us at info@yikesinc.com, we can take a look first hand and see what might be going wrong.

Thanks,
Evan
